sudo: required
services:
    - docker

before_install:
    - docker build -t richardfans/docker-react -f Dockerfile.dev .

script:
    - docker run richardfans/docker-react npm run test -- --watchAll=false --coverage